### ISSUE TITLE
No card type configured

### ISSUE THREAD

**Issue by jankete** [sbryfcz/harmony-card#12]
Hi, I just installed the component via HACS and did the configuration in Lovelace. But all I get is "No card type configured"

![Screenshot_20200204-211640](https://user-images.githubusercontent.com/22338766/73783350-d656d180-4793-11ea-8e93-036a0f7f73c4.png)

What might be wrong here?

**Comment by mcowger** [comment]
Sounds like the config in ui-lovelace.yaml is not correct.

What did you add to your resources section, and whats the path for the card on disk?

**Comment by sbryfcz** [comment]
Very weird. Are you sure HACS put the proper resource in the resources yaml config?

**Comment by mcowger** [comment]
I will say HACS never puts the right paths in my resource config.

**Comment by jankete** [comment]
The config entry was done by HACS ans looks like this

```
  - type: module
    url: /community_plugin/garbage-collection-card/garbage-collection-card.js
  - type: module
    url: /community_plugin/harmony-card/harmony-card.js
  - type: module
    url: /community_plugin/swipe-glance-card/swipe-glance-card.js
```
The path on the filesystem is:
```
/www/community/harmony-card/harmony-card.js
```

The path "/www/community/" is the same for the other plugins installed via HACS - and they working fine (see examples above). So I cannot confirm this:

>  I will say HACS never puts the right paths in my resource config.

**Comment by ludeeus** [comment]
Resources is correct, HACS will **always** use the correct path.

_users will not_

The issue here is missing card type.
You are using a manual card from the UI, most card examples are not shown for that.

Remove `- ` before type, and adjust the rest of the config to match the new indents.

**Comment by jankete** [comment]
That did it, thanks!
