### ISSUE TITLE
change colors of xbox buttons

### ISSUE THREAD

**Issue by youareme7** [sbryfcz/harmony-card#13]
Love this remote I've been looking for something all in one for a while so thanks! I'd like to be able to change the colors of the buttons, it's a small/low priority thing to be sure but figure I'd mention. I re-assigned some of the xbox buttons once I got the card to change icons/functions but they remain the color of the original buttons:

![image](https://user-images.githubusercontent.com/5589167/73859948-75b1ae00-4800-11ea-93ab-b793ac06db10.png)

**Comment by sbryfcz** [comment]
Good idea. Let me think about that. I'll try to get back to you shortly with my thoughta

**Comment by sbryfcz** [comment]
I'm thinking about two different competing ideas. One is to add a style attribute on the buttons. And users can configure whatever css style they want. But that might be a bit heavy for most use cases. So I'm thinking a simple color attribute which can take a rgb value may be good enough. Thoughts?

**Comment by youareme7** [comment]
I think the color attribute would be enough, with the icon attribute that's quite flexible, I can't say I know what else you get with the full css style, thanks for taking a look at it!

**Comment by sbryfcz** [comment]
Great. Should be a minor change to support color. I'll try to add this weekend.

**Comment by sbryfcz** [comment]
This should be enabled in the most recent release 0.10.0. Please let me know if this works for you.

**Comment by colfin22** [comment]
Is there a way of rejoicing colour or setting icons to their default colour? I've set some of the Xbox row set to white #FFFFFF but I have an automation that sets dark/light themes and white doesn't work with the light theme as it would need to be grey like the rest of the icons
