### ISSUE TITLE
D-pad buttons not working 

### ISSUE THREAD

**Issue by colfin22** [sbryfcz/harmony-card#14]
The D-pad buttons do not work for me, here's my config
https://pastebin.com/492wkQBJ

**Comment by colfin22** [comment]
In fact only the volume buttons work, play pause etc also does not work

**Comment by colfin22** [comment]
I got this working for my setup like this

https://pastebin.com/wyYxAaZx

**Comment by colfin22** [comment]
Actually this is only working for the watch Tv activity, the watch Mibox activity does not work and I can't figure why

**Comment by sbryfcz** [comment]
Sorry for the delay. For the mibox one, it looks like you are using the wrong device name. I believe the name should be `Mibox` but you have it set to `Watch Mibox` (which is the activity).

**Comment by colfin22** [comment]
Closing this, I got it sorted. My config was correct it was a Harmony issue, I had to delete and re-add the device and activity as the hub had lost it's bluetooth pairing
