### ISSUE TITLE
Add an extra row of colour-coded buttons to suit satellite box and TV remote

### ISSUE THREAD

**Issue by colfin22** [sbryfcz/harmony-card#15]
Satellite boxes and TV's use generic red, green, yellow and blue colour-coded buttons for their functions to match onscreen commands. Could you add an extra line of buttons for these.

My harmony has them mapped as       "Red","Green","Yellow","Blue"

**Comment by jes1417** [comment]
I second this, although there needs to be more buttons for satellite and cable boxes, like DVR or list for recorded content and also a guide and menu button. I currently have a working remote using Harmony states along with conditional cards on those states showing many button-cards allowing me control of whatever activity I am watching.

I would want to see the satellite buttons when I am on my watch TV activity and not the Xbox and same goes for Xbox buttons when I am playing Xbox not the satellite buttons. Is there any way to make the buttons show up on certain harmony activities?

**Comment by scooper1** [comment]
I think it would be best with say 5x4 matrix of icons instead the of current fixed icons these could be defaulted to show the current dpag layout and xbox buttons This would then meet needs of current users


Sent from Yahoo Mail on Android 
 
  On Sat, 8 Feb 2020 at 15:57, jes1417<notifications@github.com> wrote:   
I second this, although there needs to be more buttons for satellite and cable boxes, like DVR or list for recorded content and also a guide and menu button. I currently have a working remote using Harmony states along with conditional cards on those states showing many button-cards allowing me control of whatever activity I am watching.

I would want to see the satellite buttons when I am on my watch TV activity and not the Xbox and same goes for Xbox buttons when I am playing Xbox not the satellite buttons. Is there any way to make the buttons show up on certain harmony activities?

**Comment by sbryfcz** [comment]
I like the idea of allowing rows or grids of buttons to be added. Let me think about it a bit and I'll try working on it shortly.

**Comment by sbryfcz** [comment]
Sorry for the delay....life has been a bit crazy. I could actually use some help here. Do you have a proposed change to what configuration might be like to facilitate this functionality?

**Comment by 1ntroduc3** [comment]
Hi, I'd also love this. Also an addition with numpad (0-9) would be great for using it as a real TV remote.

Thanks!
