### ISSUE TITLE
Can't Unmute Volume

### ISSUE THREAD

**Issue by jwelvaert** [sbryfcz/harmony-card#17]
Muting the volume works great but I can't unmute the volume. Tried pressing the mute button again, volume up and volume down buttons but the sound never comes back on. Version Installed: 0.10.0

**Comment by sbryfcz** [comment]
Do the volume up and down work normally before you mute? What device are you using (out of curiosity).

**Comment by jwelvaert** [comment]
Yes. That part and the slider work great.

**Comment by WhiteNoseThunderPants** [comment]
I am having the same problem. My device is an Onkyo TX-NR676. The volume up and down work until I hit mute. If I hit volume up or volume down after muting, then it un mutes and moves the slider one up or down from the volume before it was muted.

**Comment by coolweb** [comment]
Yes same for me, I use Sonos devices and unable to unmute with volume up/down or the slider.
