### ISSUE TITLE
Are colors really changeable? 

### ISSUE THREAD

**Issue by askusbloodfist** [sbryfcz/harmony-card#22]
I have the following code you Y And everythign does what i want exept the color.
Is the coloring realy working on xayb=?  I myself cant cange the colors. managed to do any other option. 

      'y':
        command: Home
        device: Apple tv
        hide: false
        icon: 'mdi:monitor'
        color: '#fffffff'

**Comment by Krocko** [comment]
There is one 'f' to much for the `color:`
Try with `#ffffff`

**Comment by askusbloodfist** [comment]
Yeh just a typo by me, Im doing the following. but ABXY are always set colors no matter what i do

`activities:
  - buttons:
      a:
        color: '#ffffff'
        command: Menu
        device: Apple tv
        hide: false
        icon: 'mdi:menu'
      b:
        color: '#ffffff'
        command: Home
        device: Apple tv
        hide: true
      back:
        hide: false
      dpad_center:
        command: Select
        device: Apple tv
        hide: false
      dpad_down:
        hide: false
      dpad_left:
        hide: false
      dpad_right:
        hide: false
      dpad_up:
        hide: false
      pause:
        hide: false
        icon: 'mdi:pause'
      play:
        hide: false
        icon: 'mdi:play'
      skip_back:
        hide: false
        icon: 'mdi:skip-previous'
      skip_forward:
        hide: false
        icon: 'mdi:skip-next'
      volume_down:
        hide: false
        icon: 'mdi:volume-medium'
      volume_mute:
        hide: false
        icon: 'mdi:volume-off'
      volume_up:
        hide: false
        icon: 'mdi:volume-high'
      x:
        color: '#ffffff'
        hide: true
      xbox:
        action: call-service
        hide: false
        icon: 'mdi:gamepad-variant'
        service: script.turn_on
        service_data:
          entity_id: script.gamemode
      'y':
        color: '#ffffff'
        command: Home
        device: Apple tv
        hide: false
        icon: 'mdi:monitor'
    device: Apple tv
    name: Apple tv
    volume_device: Ljud-videomottagare
  - buttons:
      a:
        color: '#ffffff'
        hide: true
        icon: 'mdi:menu'
      b:
        color: '#ffffff'
        hide: true
      back:
        hide: false
      dpad_center:
        hide: false
      dpad_down:
        hide: false
      dpad_left:
        hide: false
      dpad_right:
        hide: false
      dpad_up:
        hide: false
      pause:
        hide: false
        icon: 'mdi:pause'
      play:
        hide: false
        icon: 'mdi:play'
      skip_back:
        hide: false
        icon: 'mdi:skip-previous'
      skip_forward:
        hide: false
        icon: 'mdi:skip-next'
      volume_down:
        hide: false
        icon: 'mdi:volume-medium'
      volume_mute:
        hide: false
        icon: 'mdi:volume-off'
      volume_up:
        hide: false
        icon: 'mdi:volume-high'
      x:
        color: '#ffffff'
        hide: true
      xbox:
        action: call-service
        color: '#ffffff'
        hide: false
        icon: 'mdi:gamepad-variant'
        service: script.turn_on
        service_data:
          entity_id: script.gamemode
      'y':
        hide: true
    device: Htpc
    name: Htpc
    volume_device: Ljud-videomottagare
  - buttons:
      a:
        hide: true
      b:
        hide: true
      back:
        hide: false
      dpad_center:
        hide: false
      dpad_down:
        hide: false
      dpad_left:
        hide: false
      dpad_right:
        hide: false
      dpad_up:
        hide: false
      pause:
        hide: false
        icon: 'mdi:pause'
      play:
        hide: false
        icon: 'mdi:play'
      skip_back:
        hide: false
        icon: 'mdi:skip-previous'
      skip_forward:
        hide: false
        icon: 'mdi:skip-next'
      volume_down:
        hide: false
        icon: 'mdi:volume-medium'
      volume_mute:
        hide: false
        icon: 'mdi:volume-off'
      volume_up:
        hide: false
        icon: 'mdi:volume-high'
      x:
        hide: true
      xbox:
        action: call-service
        color: '#ff0000'
        hide: false
        icon: 'mdi:gamepad-variant'
        service: script.turn_on
        service_data:
          entity_id: script.gamemode
      'y':
        hide: true
    device: Tv
    name: Tv
    volume_device: Ljud-videomottagare
  - buttons:
      a:
        hide: true
      b:
        hide: true
      back:
        hide: false
      dpad_center:
        hide: false
      dpad_down:
        hide: false
      dpad_left:
        hide: false
      dpad_right:
        hide: false
      dpad_up:
        hide: false
      pause:
        hide: false
        icon: 'mdi:pause'
      play:
        hide: false
        icon: 'mdi:play'
      skip_back:
        hide: false
        icon: 'mdi:skip-previous'
      skip_forward:
        hide: false
        icon: 'mdi:skip-next'
      volume_down:
        hide: false
        icon: 'mdi:volume-medium'
      volume_mute:
        hide: false
        icon: 'mdi:volume-off'
      volume_up:
        hide: false
        icon: 'mdi:volume-high'
      x:
        hide: true
      xbox:
        action: call-service
        color: '#ffffff'
        hide: false
        icon: 'mdi:gamepad-variant'
        service: script.turn_on
        service_data:
          entity_id: script.gamemode
      'y':
        hide: true
    device: PS4
    name: PS4
    volume_device: Ljud-videomottagare
buttons:
  a:
    hide: true
  b:
    hide: true
  back:
    hide: true
  dpad_center:
    hide: true
  dpad_down:
    hide: true
  dpad_left:
    hide: true
  dpad_right:
    hide: true
  dpad_up:
    hide: true
  pause:
    hide: true
  play:
    hide: true
  skip_back:
    hide: true
  skip_forward:
    hide: true
  volume_down:
    hide: false
  volume_mute:
    hide: false
  volume_up:
    hide: false
  x:
    hide: true
  xbox:
    hide: true
  'y':
    hide: true
entity: remote.vardagsrum
scale: 1.4
type: 'custom:harmony-card'
`

**Comment by askusbloodfist** [comment]
Sins i could not se what might be right infront of me or if the card wont allow you to change the colors of the ABYX Buttons i changed code in the JS files in the js and gz

\www\community\harmony-card\harmony-card.js
.. harmony-card.js.gz

The Rows i changed 

`                ${this.renderIconButton(buttonConfig['a'], currentDevice, "grid-column: 4; grid-row: 2; color: #ffffff;")}
                ${this.renderIconButton(buttonConfig['b'], currentDevice, "grid-column: 5; grid-row: 2; color: #ffffff;")}
                ${this.renderIconButton(buttonConfig['x'], currentDevice, "grid-column: 6; grid-row: 2; color: #ffffff;")}        
                ${this.renderIconButton(buttonConfig['y'], currentDevice, "grid-column: 7; grid-row: 2; color: #ffffff;")}     `

#ffffff is what u can change to whatever colors you are looking for. Glhf. Hope for updates that makes this easyer or changeable @ all.

**Comment by sbryfcz** [comment]
Pull requests are always considered.

**Comment by sbryfcz** [comment]
I didnt have any issues changing the color of the 'y' button with configuration:
```yaml
buttons:
  y:
    color: #ffffff
```
