### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by nikiyao** [sbryfcz/harmony-card#25]
After updating to .110b0 all my icons are missing

**Comment by Krocko** [comment]
Same for me

**Comment by temphassio** [comment]
Me also. Icons disappeared when updating from 109.6 to 110.0 after it released this morning.  There still seem to be buttons but no icons.

**Comment by jaycustine** [comment]
Same boat.  Just installed release 110 this morning.

**Comment by jayhassio** [comment]
Same here, installed release 110 this morning and icons gone.

**Comment by fernandex00** [comment]
Same here

**Comment by werfpsa** [comment]
Same for me, just updated to 110.0

**Comment by skank01** [comment]
Same for me, guess this is not ready for 110

**Comment by ronniebee** [comment]
Same here, can you please help. It's one of my favourite add-ons on my HA system. Since moving to 110.0 it isn't working....  HELPPPPPP :-)

**Comment by reesion** [comment]
As per the changes: https://github.com/home-assistant/frontend/pull/4379
But replacing all (11) paper-icon-button with ha-icon-button in harmony-card.js doesn't seems to work for me.

**Comment by werfpsa** [comment]
Does somebody has an idea for a solution (direction)? Seems like the developer is not reacting....

**Comment by reesion** [comment]
> harmony-card.

You will also need to delete harmony-card.gz file located in the folder. Hacs will serve the browser the gz file if it’s there in order to save bandwidth. If it’s not there, it will use the .js file

**Comment by werfpsa** [comment]
Super. This works! Just find and replace paper-icon-button with ha-icon-button.
Now only the 'color' buttons are missing( red - blue -green and yellow)...

**Comment by chris8837** [comment]
Looks like this solution works great.  Thanks!!  I was wondering if anyone figured out how to scale the icons now?  Just seems to increase the border and not the actually icons themselves?

**Comment by skank01** [comment]
Strange but doesnt fix it for me
I did change all icons to ha-icon-button
but i cant find the gz file

**Comment by chris8837** [comment]
config/www/community/harmony-card

Mine was here
