### ISSUE TITLE
Icons not scaling

### ISSUE THREAD

**Issue by Cassock** [sbryfcz/harmony-card#30]
Thanks for fixing the missing icons, however, it doesn't appear they're scaling as they should. Only the spacing between them scales. See the example here with scaling at 1 vs 2.
![image](https://user-images.githubusercontent.com/15901832/83211428-17039d80-a12b-11ea-85bd-9e90190a6699.png)

**Comment by temphassio** [comment]
I'm having the same issue.

**Comment by firstdominator** [comment]
Same here. Is this github maintained?

Thanks

**Comment by Cassock** [comment]
Sadly, it doesn't look that way.

**Comment by sbryfcz** [comment]
I've been super busy with other project work. A PR is always considered. Otherwise, you'll have to look elsewhere at the moment. Thanks for understanding.

**Comment by sbryfcz** [comment]
I think I found the issue. Will try to post a fix asap.

**Comment by sbryfcz** [comment]
Should be fixed now in latest version.
