### ISSUE TITLE
No Longer in Hacs.

### ISSUE THREAD

**Issue by kiwidutchhome** [sbryfcz/harmony-card#33]
A few months ago I believe I installed this using HACS, but I no longer find it there. 

I deleted it because I was trying few things out, but now want to reinstall it. I can't find it anymore.

How should I reinstall it?

Thanks.

**Comment by TheFes** [comment]
I installed it from HACS without issues yesterday.

**Comment by baizinger** [comment]
It is gone for me too. :(

**Comment by kiwidutchhome** [comment]
I asked on a Discord chat. 

Go to HACS, and if you click on the orange + button it brings up repositories that are not on the front HACS page. Type Harmony in the search at the top and it harmony-card will come up. You can install it from there.

**Comment by hurricanepkt** [comment]
When i upgraded from 0.114.0 to 0.114.1 it showed up

**Comment by sbryfcz** [comment]
I verified it appears to in the HACS list.

**Comment by ljmerza** [comment]
I cannot find it in the HACS store. I've searched for harmony, harmony-card, and logitech. When I try to add this card manually it says already exists. Where is this card??
