### ISSUE TITLE
Extra options for activities: icon

### ISSUE THREAD

**Issue by HeaDBanGer84** [sbryfcz/harmony-card#37]
It would be nice to replace  the activity text with an icon. Perhaps just by adding a new optional property to activities.

**Comment by sbryfcz** [comment]
This is actually not quite as straightforward as I had hoped. Still investigating some components that could serve this purpose.

**Comment by mattieha** [comment]
@sbryfcz Thank you for your work on this card, I made a PR (#49 ) to add icons.

**Comment by 1ntroduc3** [comment]
> @sbryfcz Thank you for your work on this card, I made a PR (#49 ) to add icons.

And I tried it, works amazing!!

**Comment by HeaDBanGer84** [comment]
This is great news...hope this could be soon merged and released

**Comment by nibblerrick** [comment]
This is great, I always wanted to make a featurerequest for this but havent got around doing it actually... Works perfectly, thank you very much!
