### ISSUE TITLE
need help building

### ISSUE THREAD

**Issue by ItzYanick** [sbryfcz/harmony-card#39]
I just downloaded your repository and wanted to build it. But as soon as i hit enter, nodejs spits out like 600 errors on eslint (not even a joke. it shows 681 errors). Maybe someone can help me out here.

**Comment by sbryfcz** [comment]
Yeah. I'm not sure what is going on. Please try to ignore the lint errors as they are plentiful (and frankly I never had a goal to stay in line with the lining guidelines I got the boilerplate starter code from). I typically run `npm run start` and point my local HA instance to that served up file while debugging.

**Comment by ItzYanick** [comment]
okay i just tried using `npm run start` and run into another issue:
now it shows me following error:
`[!] (plugin rpt2) Error: /home/yanick/Documents/Projects/harmony-card/src/harmony-card.ts(80,19): syntax error TS1109: Expression expected.`
maybe you have a quick fix or workaround for this one too

**Comment by sbryfcz** [comment]
Hmmmmm that's an odd one. I was JUST doing a bit of work on this and it compiled and started up great. What version of non are you running? I assume you ran an npm install first.

**Comment by ItzYanick** [comment]
Of course i ran npm install haha. I first tested it on node v14.14.0 but when i saw you were using node v8 (as written in the readme file) i installed v8.17.0 and there was the same issue

**Comment by ItzYanick** [comment]
Okay i just delete node_modules and reinstalled it. Now i got a other error
 `[!] (plugin rpt2) Error: /home/yanick/Documents/Projects/harmony-card/src/harmony-card.ts(166,13): semantic error TS2345: Argument of type '{ hasHold: boolean; hasDoubleTap: boolean; repeat: number | undefined; }' is not assignable to parameter of type 'ActionHandlerOptions'.
  Object literal may only specify known properties, and 'hasDoubleTap' does not exist in type 'ActionHandlerOptions'.`

**Comment by sbryfcz** [comment]
Hmmmm. I'll try to investigate.

**Comment by ItzYanick** [comment]
Okay. Thank you very very much then already 🙏
Hope you can find out whats going wrong here haha

**Comment by sbryfcz** [comment]
Hmmmmm. I wiped out my node_modules and dist folders. Then I ran 
`npm install` followed by `npm run start`. Everything compiled fine for me.....

Not sure it matters but here are my current npm and node versions

$ npm -v
6.14.7

$ node -v
v10.15.3

**Comment by ItzYanick** [comment]
could you paste your package-lock.json onto pastebin and then on here maybe? Maybe i can find something comparing mine with yours.

**Comment by sbryfcz** [comment]
Just pushed it to master....thought it was already there. Hope that helps.

**Comment by ItzYanick** [comment]
IT WORKED! I just swapped out my package-lock.json file with yours. Then i just ran `npm install` and now it works hahaha
It seems your package.json in the repo is not equal to your local installation with your package-lock.json

**Comment by ItzYanick** [comment]
So I made a fork of your repo and added a numpad / keypad for this card. I saw there is an open issue facing that. If you want I can document the new settings and make a pull request so that you can add it to the code if you like :D
