### ISSUE TITLE
Optional: Hide activities

### ISSUE THREAD

**Issue by Partovic** [sbryfcz/harmony-card#44]
I would appreciate an option to hide the Activity buttons. This way it could be possible to embed the device buttons into another layouts.
![buttons](https://user-images.githubusercontent.com/20333797/97007729-2227f180-1542-11eb-8166-297f58d1ad87.png)

**Comment by skank01** [comment]
I agree, i was just looking for that too !

**Comment by mattieha** [comment]
Hi, I made a PR (#49) which adds the option to hide the activities row.

**Comment by skank01** [comment]
Any idea when this will be available?

**Comment by 1ntroduc3** [comment]
> Any idea when this will be available?

I made a fork available. That one works. Check my profile

**Comment by Krocko** [comment]
@1ntroduc3 is it possible to hide the volume slider?
And can you make an option to add a stop button next to the Play button?

**Comment by skank01** [comment]
> > Any idea when this will be available?
> 
> I made a fork available. That one works. Check my profile

How can i install it easily?
Cause the different steps mentioned is for me kinda chines :p
