### ISSUE TITLE
Not Loaded

### ISSUE THREAD

**Issue by SHadley1138** [sbryfcz/harmony-card#48]
hi there
im quite new to HACS, but i cannot get this card to load.  It just has a red bar, and Not Loaded
rebooted a million times
a bit lost on how to troubleshoot it, any help would be appreciated
![image](https://user-images.githubusercontent.com/45368351/100119849-3af03380-2e6f-11eb-8ff3-43101a8b7114.png)

**Comment by notryanfraser** [comment]
```
frontend:
  extra_module_url:
    - /local/community/harmony-card/harmony-card.js
```

I added that to my configuration.yaml (if you already have frontend.extra_module_url, just add the line item for the JS file) and that seemed to work. Getting my card to render on the other hand...

hope this helps :D

**Comment by SHadley1138** [comment]
Thanks for that.  It took the config, but nothing

Thanks for the help.  I’ll keep searching

**Comment by notryanfraser** [comment]
That's disappointing,  does your web browser console show anything like this (or perhaps an error that it can't find the javascript?)

![image](https://user-images.githubusercontent.com/47481699/100249793-961f3600-2f02-11eb-87cb-0ef190887695.png)

**Comment by lee-js** [comment]
> ```
> frontend:
>   extra_module_url:
>     - /local/community/harmony-card/harmony-card.js
> ```
Where did you find this information? I can't see this anywhere in the instructions.

What is in the instructions doesn't actually work anyway. I had to use /hacsfiles/harmony-card/harmony-card.js.

Even with that loaded I can't get the card type to show up when adding a new card to Lovelace.

**Comment by notryanfraser** [comment]
I ran into the same issues with the documentation.  I ended up just using
some deductive reasoning and loaded it in where it was in the file system
as an extra_modulre_url. It seemed to pick up after that.  I took a bit of
fidgeting with but I have got the harmony cards to load finally.

[image: image.png]
