### ISSUE TITLE
Activities dont wrap around when mutliple added

### ISSUE THREAD

**Issue by sbryfcz** [sbryfcz/harmony-card#5]
When a user is adding many activites, they dont display properly. They should wrap around to the next line.

**Comment by sbryfcz** [comment]
Fixed in latest release 0.7.0

**Comment by SmartHomeFanatic** [comment]
Hi!
I'm running version 0.7.0 and added 5 activities. Their names aren't wrapped around, unfortunately.
![grafik](https://user-images.githubusercontent.com/41552156/73613800-880dcb00-45f9-11ea-8adc-dd7eef4e1d4e.png)

**Comment by sbryfcz** [comment]
Hmmmm. Please share you card yaml configuration. And could triple check you are running the latest version of the card.

**Comment by SmartHomeFanatic** [comment]
@sbryfcz 
![grafik](https://user-images.githubusercontent.com/41552156/73635365-ab6d6000-4663-11ea-8a84-2cde2b4f5162.png)

`type: 'custom:harmony-card'
entity: remote.harmony_hub
activities:
  - name: Fernsehen
    device: Sagemcom DVR
    volume_device: Panasonic TV
  - name: Fire TV
    device: Amazon Fire TV
    volume_device: Panasonic TV
  - name: Xbox One
    device: Xbox
    volume_device: Panasonic TV
  - name: Nintendo
    volume_device: Panasonic TV
  - name: Chromecast
    volume_device: Panasonic TV
volume_entity: media_player.wohnzimmer_3`

**Comment by SmartHomeFanatic** [comment]
@sbryfcz 
I've uninstalled the plugin completely via HACS and reinstalled it.
That did the trick, don't know why.

Thanks for that wonderful plugin and your help!

**Comment by sbryfcz** [comment]
Woooooo! Glad that worked because I was at a loss. Sometimes clearing the browser cache can help as well. Glad you got it resolved. Happy to hear any other feedback you might have.
