### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by andymarden** [sbryfcz/harmony-card#50]
I don't understand the relationship between activity, device and volume. The whole point of Harmony is that an activity hides the devices from you including what implements volume control. I was expecting to be able to use an activity and the harmony hub knows what devices are involved and what implements volume control behind the scenes.

What am I missing here?

**Comment by mattieha** [comment]
Unfortunately the harmony api doesn't provide this data. It provides all devices, all activities and what the current activity is, but not which devices are used by a certain activity.

That's why u have to config this yourself.
