### ISSUE TITLE
Custom card not found

### ISSUE THREAD

**Issue by norgan** [sbryfcz/harmony-card#56]
Hi, 

I have installed this via hacs and it is not allowing me to add this custom card type to lovelace. I tried as stock plus also adding the resource manually. All referenced files seem to be there. 
Is there a dependency i'm missing? 
`No card type configured
- type: 'custom:harmony-card'
  entity: remote.living_room_hub
  volume_entity: media_player.living_room
  scale: 1.25
  activities:
    - name: Play Xbox One
      device: Microsoft Xbox One
    - name: Listen to Music
      device: Onkyo AV Receiver`

**Comment by norgan** [comment]
/hacsfiles/harmony-card/harmony-card.js type javascript module

**Comment by frznfngrs** [comment]
I am having the same issue.  Not sure whats going on

**Comment by ianfretwell** [comment]
Same issue for me.

Is it because HACS adds the resource as :-
/hacsfiles/harmony-card/harmony-card.js

whereas the notes here state:-
/community_plugin/harmony-card/harmony-card.js

**Comment by Ebdirtrider** [comment]
I tried both of these as resource but still get card not found.  Installed from HACS.

/hacsfiles/harmony-card/harmony-card.js

whereas the notes here state:-
/community_plugin/harmony-card/harmony-card.js

**Comment by Windyo** [comment]
Same here

**Comment by vakilando** [comment]
same here

**Comment by 35gh** [comment]
I'm experiencing the same issue. The card did show up when I added it manually with the right activities.
