### ISSUE TITLE
[Bug] Icons don't work in HA 2021.11.x

### ISSUE THREAD

**Issue by drinfernoo** [sbryfcz/harmony-card#64]
The icons I've specified are all `mdi` icons, but none of my buttons show up at all with this card... probably due to some changes they made with icons in order to implement the icon picker.

![image](https://user-images.githubusercontent.com/2319508/139742237-c7e3bdca-7016-421d-9aa7-5cc3d43c6756.png)

**Comment by drinfernoo** [comment]
The buttons still work, as I can see the outline when I hover over them, but the icons just don't show up.

**Comment by Krocko** [comment]
I have the same problem. 
But I think there would be no reaction from the developer. 
The last time he was active here is a long time ago.

**Comment by tetragram55** [comment]
I have the same problem.

**Comment by krelltunez** [comment]
Same here.

**Comment by mwhdc** [comment]
Looks like many custom cards are having this issue.

https://github.com/home-assistant/frontend/issues/10521

Seems fairly simple to fix in a fork if the original dev is no longer checking in.

**Comment by kksligh** [comment]
same issue here

**Comment by mwhdc** [comment]
> same issue here

@kksligh See @kalhimeo's fork for a fix.

https://github.com/kalhimeo/harmony-card/releases/tag/1.1

**Comment by kdoh82** [comment]
I updated to the latest release and am still seeing the icons missing. Anyone else seeing the same?

**Comment by drinfernoo** [comment]
@kdoh82 Reload your browser cache.

**Comment by kdoh82** [comment]
@drinfernoo Right on.. thanks for the reminder that fixed it for me.
