### ISSUE TITLE
Center button command

### ISSUE THREAD

**Issue by Toolhead** [sbryfcz/harmony-card#69]
For my receiver the command from the center button is "Enter", for my other devices the center button it is "Select".
The button sends "Select", which is fine for all devices, except when the device is the receiver.
Is there a way that the center button sends "Enter" when the active device is the receiver?

**Comment by simonesolda** [comment]
Same for me.

**Comment by werfpsa** [comment]
You can allocate commands per activity to a button and device. So this should be no problem, see example below:
    - buttons:
        dpad_center:
          command: Enter
        skip_back:
          command: ChapterPrev
        skip_forward:
          command: ChapterNext
        xbox:
          command: Home
          icon: mdi:home
      device: OPPO UDP-203
      name: Oppo app
      icon: mdi:ipod
      volume_entity: media_player.denon_avc_x8500h_

**Comment by simonesolda** [comment]
Thank you for the confirmation that is possible to use a "per activity button" config.
Can you update the docs with an easy example? The one that is present is a "global" custom button and it's not very clear how to do per activity.

**Comment by werfpsa** [comment]
The presented one is a activity with buttons different from the 'global' definition:
The name of the activity is Oppo app. You can also add a seperate device per button.
''''
    - buttons:
        dpad_audio:
          command: Audio
        dpad_center:
          command: Enter
        dpad_menu:
          command: Pop-UpMenu
        dpad_option:
          command: Option
        dpad_tmenu:
          command: TopMenu
        skip_back:
          command: ChapterPrev
        skip_forward:
          command: ChapterNext
        xbox:
          command: Home
          icon: mdi:home
      device: OPPO UDP-203
      name: Oppo app
      icon: mdi:ipod
      volume_entity: media_player.denon_avc_x8500h_2
''''

**Comment by Toolhead** [comment]
I currently have this:

type: custom:harmony-card
entity: remote.harmony_hub
volume_entity: media_player.receiver
scale: 1.25
activities:
  - name: TV
    device: Arris DVR
  - name: Apple TV
    device: Tv Apple
  - name: Radio
    device: AV-ontvanger Onkyo
  - name: CD
    device: Samsung Blu Ray
  - name: Bluray
    device: Samsung Blu Ray
  - name: Internet radio
    device: AV-ontvanger Onkyo
buttons:
  a:
    icon: mdi:checkbox-blank-circle
    device: AV-ontvanger Onkyo
    command: Enter
    hide: false
    color: null
  xbox:
    hide: true
  b:
    hide: true
  x:
    hide: true
  'y':
    hide: true
show_error: false
show_warning: false


Can anyone show me what to change so that when current activity is "Internet radio" the center button gives "Enter"?
Thanks in advance.

**Comment by werfpsa** [comment]
add the following lines to the buttons section of Internet radio:
        dpad_center:
            icon: mdi:checkbox-blank-circle
            device: AV-ontvanger Onkyo
            command: Enter

**Comment by werfpsa** [comment]
type: custom:harmony-card
entity: remote.harmony_hub
volume_entity: media_player.receiver
scale: 1.25
activities:

- name: TV
  device: Arris DVR
- name: Apple TV
  device: Tv Apple
- name: Radio
  device: AV-ontvanger Onkyo
- name: CD
  device: Samsung Blu Ray
- name: Bluray
  device: Samsung Blu Ray
- name: Internet radio
  device: AV-ontvanger Onkyo
  buttons:
    dpad_center:
    icon: mdi:checkbox-blank-circle
   command: Enter
buttons:
a:
icon: mdi:checkbox-blank-circle
device: AV-ontvanger Onkyo
command: Enter
hide: false
color: null
xbox:
hide: true
b:
hide: true
x:
hide: true
'y':
hide: true
show_error: false
show_warning: false

**Comment by Toolhead** [comment]
Unfortunately it doe not work.
I can put the lines and save it.
But when I open the code again there are "null" texts added:

  - name: Internet radio
    device: AV-ontvanger Onkyo
    buttons: null
    dpad_center: null
    icon: mdi:checkbox-blank-circle
    command: Enter

**Comment by werfpsa** [comment]
Do you indent with 2 spaces after buttons and after dpad_center?

**Comment by Toolhead** [comment]
I did not, but now it is working.
Thank you so much!!!
