### ISSUE TITLE
Blank card

### ISSUE THREAD

**Issue by scooper1** [sbryfcz/harmony-card#7]
log  gives following error

ERROR (MainThread) [hacs] Tried to serve up '/config/www/community/harmony-card/index.m.js.map' but it does not exist

the file does not exist - any ideas on what i am doing wrong ?
installed via hacs

**Comment by sbryfcz** [comment]
Odd. Is that the resource that was included? Can you check your raw config? The resource should typically be /community_plugin/harmony-card/harmony-card.js

**Comment by scooper1** [comment]
it was a problem caused by card-mod plugin
