### ISSUE TITLE
Possible to add more buttons?!

### ISSUE THREAD

**Issue by erkr** [sbryfcz/harmony-card#76]
Just found this nice card for harmony, thanks!
One limiting factor for me is that I need at least 3 more buttons then currently available (to be able to operate my IPTV box):
-Stop
-Menu
-Info
(I already mapped the Xbox a,b,x and y buttons to red, green, yellow and blue commands)
<del> Additionally I would be great if buttons could be defined per activity. But I can imagine that is a more serious change than adding more commands. </del> --> that is already possible, sorry.
Sincerely
Eric

**Comment by erkr** [comment]
Please reopen. Still would love to have a few extra buttons

**Comment by werfpsa** [comment]
[
![C15A6E48-3AED-4EF6-B0AC-75BE86577D54](https://user-images.githubusercontent.com/34813015/196386263-17efd328-6487-4109-b127-79af85f91dd5.jpeg)
](url)
I have doen this myself. It’s not complex, but you have to do it again after Evert plug-in update…

**Comment by erkr** [comment]
Exactly that is what I would like to do 👍
