### ISSUE TITLE
Add the Ability to have Different Per Activity Commands

### ISSUE THREAD

**Issue by PablaV** [sbryfcz/harmony-card#80]
Was wondering if it is possible to have different button commands based on what activity is on. For example if the Watch TV command is on the select button sends the select command to my DVR and if the Watch Apple TV command is on that same button now sends the select command to my Apple TV instead.

**Comment by werfpsa** [comment]
This is standard functionality and basic. See documentation with examples

**Comment by PablaV** [comment]
Ah I get it now, I didn't know you could have activity level button commands. Thought only volume device could be activity level.
