### ISSUE TITLE
Card does not render

### ISSUE THREAD

**Issue by BjornHoorelbeke** [sbryfcz/harmony-card#82]
Installed the custom card using HACS
Reference is added : "/hacsfiles/harmony-card/harmony-card.js?hacstag=2375327500141"
I use the examples to create a new card
`type: custom:harmony-card
entity: remote.living_room_hub
volume_entity: media_player.living_room
scale: 1.25
activities:
  ...
buttons:
  ....`

this is inserted in the html, and nothing is rendered
`<div class="column"><harmony-card></harmony-card></div>`

Any idea what is going wrong?

**Comment by claudermilk** [comment]
I am running into the same issue. I have had it installed and it was working with the simple example card. Now it won't render any more.
