### ISSUE TITLE
Long Press Repeat Button Presses

### ISSUE THREAD

**Issue by sbryfcz** [sbryfcz/harmony-card#9]
Similar to harmony remotes, when a user presses and holds a button, it should repeatedly press the button. Example volume up and volume down should continuously increase decrease volume.

**Comment by hafnerra** [comment]
Is there a solution for this Problem?

**Comment by 1ntroduc3** [comment]
This would be great, so we can also use the "hold" for select button. now there's a "long press"menu behind some tv remote buttons, and we can't get that with this amazing card.
