### ISSUE TITLE
Volume Slider Missing After Upgrading to 11.1

### ISSUE THREAD

**Issue by Spiffieman** [sbryfcz/harmony-card#91]
Hi there - after upgrading to 2023.11.1 today, I noticed that the volume slider bar is missing from my harmony card. Any thoughts on that?

![image](https://github.com/sbryfcz/harmony-card/assets/76534297/b86c8f99-25b8-4f07-8bf2-31a2872537bd)

The volume up, down, and mute buttons still work but the slider bar is just gone. 

Here is the card code (it is a conditional card). This is happening on my PC as well as my android phone. Thanks!

type: conditional
conditions:
  - entity: switch.harmony_hub_watch_tv_2
    state_not: 'off'
card:
  type: custom:harmony-card
  entity: remote.harmony_hub
  volume_entity: media_player.receiver
  scale: 1.25
  activities:
    - name: Chromecast
    - name: Shield
    - name: XBox
  buttons:
    '0':
      command: '0'
      icon: mdi:numeric-0-circle
      hide: true
    '1':
      command: '1'
      icon: mdi:numeric-1-circle
      hide: true
    '2':
      command: '2'
      icon: mdi:numeric-2-circle
      hide: true
    '3':
      command: '3'
      icon: mdi:numeric-3-circle
      hide: true
    '4':
      command: '4'
      icon: mdi:numeric-4-circle
      hide: true
    '5':
      command: '5'
      icon: mdi:numeric-5-circle
      hide: true
    '6':
      command: '6'
      icon: mdi:numeric-6-circle
      hide: true
    '7':
      command: '7'
      icon: mdi:numeric-7-circle
      hide: true
    '8':
      command: '8'
      icon: mdi:numeric-8-circle
      hide: true
    '9':
      command: '9'
      icon: mdi:numeric-9-circle
      hide: true
    a:
      command: VolumeDown
      device: Receiver
      icon: mdi:minus
      hide: true
      color: null
    b:
      command: mute
      device: Receiver
      icon: mdi:volume-off
    x:
      icon: mdi:plus
      device: Receiver
      command: VolumeUp
      color: null
      hide: true
    dpad_up:
      command: DirectionUp
      device: NVIDIA Game Console
      icon: mdi:chevron-up-circle
      hide: false
    dpad_down:
      command: DirectionDown
      device: NVIDIA Game Console
      icon: mdi:chevron-down-circle
      hide: false
    dpad_left:
      command: DirectionLeft
      device: NVIDIA Game Console
      icon: mdi:chevron-left-circle
      hide: false
    dpad_right:
      command: DirectionRight
      device: NVIDIA Game Console
      icon: mdi:chevron-right-circle
      hide: false
    dpad_center:
      command: Select
      device: NVIDIA Game Console
      icon: mdi:checkbox-blank-circle
      hide: false
    'y':
      command: Home
      device: NVIDIA Game Console
      icon: mdi:home
      hide: false
    back:
      command: Back
      device: NVIDIA Game Console
      hide: false
    xbox:
      hide: true
    play:
      command: Play
      device: NVIDIA Game Console
      icon: mdi:play
      hide: false
    pause:
      command: Pause
      device: NVIDIA Game Console
      icon: mdi:pause
      hide: false
    skip_forward:
      command: FastForward
      device: NVIDIA Game Console
      icon: mdi:skip-next
      hide: false
    skip_back:
      command: Rewind
      device: NVIDIA Game Console
      icon: mdi:skip-previous
      hide: false
  name: Shield Remote
  show_error: false
  show_warning: false

**Comment by Spiffieman** [comment]
Here is where it used to be:

![image](https://github.com/sbryfcz/harmony-card/assets/76534297/05283187-e8f1-4a8d-b4d0-47eb0ff44492)

**Comment by Spiffieman** [comment]
Volume slider still shows via the Denon integration: 

![image](https://github.com/sbryfcz/harmony-card/assets/76534297/e3ed2c38-f914-4911-a2ac-12d8c604a19c)

**Comment by kalhimeo** [comment]
I can confirm the problem, I had a look but unfortunately I am not able to fix that :/

**Comment by werfpsa** [comment]
I have made a work around using a conditional card for the receiver with the mini media player card. The mini media card is only visible when the receiver is on and used for the volume. The mini media card only shows the volume bar...

```
type: conditional
conditions:
  - condition: state
    entity: sensor.harmony_activity
    state_not: MF library
  - condition: state
    entity: sensor.harmony_activity
    state_not: MF CD
  - condition: state
    entity: sensor.harmony_activity
    state_not: PowerOff
  - condition: state
    entity: remote.woonkamer
    state_not: unavailable
card:
  type: custom:mini-media-player
  entity: media_player.denon_avc_x8500h
  hide:
    source: true
    info: true
    icon: true
    name: true
    power: true
    volume_level: false
    play_pause: true
```

**Comment by chrisns** [comment]
thanks for reviewing+merging @kalhimeo ! please could you push a release?

**Comment by kalhimeo** [comment]
Hi Chris, first thank you so much for the bugfix 👍 I am gonna push a release once I have found how it works :-D I have been added to this project by the creator of the card, but to be honest I am not an expert of github and how the link with HACS works :-P

**Comment by chrisns** [comment]
by the looks of things its using https://github.com/release-drafter/release-drafter so there may be a draft release created you can publish? ¯\_(ツ)_/¯

**Comment by kalhimeo** [comment]
Ok I had to go through it twice, but I think that I got it working now :-) You can try the 0.14.3 release

**Comment by chrisns** [comment]
Hero! Thanks @kalhimeo ! LGTM
