### ISSUE TITLE
Is the project down?

### ISSUE THREAD

**Issue by Astination** [sbryfcz/harmony-card#94]
Hello, I 'd like to install this card on my HA 11.4 but it seems not working...
Help really appreciated

**Comment by werfpsa** [comment]
It should work normally. What is your problem. Please give details and yaml example

**Comment by Astination** [comment]
I've made the install with HACS, but I cann't see the card in Lovelace when I push on add a card, and when I try to make a custom card and add a code like:
------------
type: 'custom:harmony-card'
entity: remote.astina_hub
volume_entity: media_player.salon
activities:
....
-----------
I got this:
"Custom element doesn't exist: harmony-card"

**Comment by werfpsa** [comment]
Have you tried a restart?

**Comment by Astination** [comment]
Yes, of course

**Comment by kalhimeo** [comment]
it looks like a problem with the web browser cache, could you try with another device (phone, tablet, other computer) ? You can also try to force a cache refresh with Ctrl + F5 or browse HA with the "private mode" of your browser.

**Comment by Astination** [comment]
Yep, you are right!

THX!!

**Comment by Astination** [comment]
Yep, you are right!

THX!!

**Comment by viseniv** [comment]
i tryed to browse home assitant with private browser and this card didn't show up. 
I get the same error as the op.

**Comment by Astination** [comment]
Have you try in your usual browser to make crtl+f5 in the same time?

**Comment by viseniv** [comment]
> Have you try in your usual browser to make crtl+f5 in the same time?

Yes, and i try with different browsers on mobile, and on pc

**Comment by viseniv** [comment]
I still having this problem, i tried to redownload but it is the same.
